version: '3.8'
services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flaskapp
      - git-server
    networks:
      - lab-webproxy

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
    networks:
      - lab-webproxy

  flaskapp:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./myapp:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - lab-webproxy

networks:
  lab-webproxy:
    driver: bridge
