name: Flask App Selenium & Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (Flask test client)
        run: pytest -k "not selenium"

      - name: Start Flask app
        run: |
          nohup python app.py &  # Make sure it binds to 0.0.0.0:5000
          sleep 5

      - name: Run Selenium integration test
        run: pytest -m selenium
